"""
Write NIfTI multi-label masks back to DICOM RTSTRUCTs for easy viewing/handling in TPS etc.
"""

import json
import logging
import os
from collections import Counter

import nibabel as nib
import numpy as np
import pydicom
from rt_utils import RTStructBuilder

logger = logging.getLogger(__name__)

MAX_ROI_NAME_LENGTH = 16 # structure name length cap in TPS

def rtstruct_tags(model_name: str):
    """
    DICOM metadata appended to output RTstruct - can be adjusted as required by application.
    """

    return {
        "StructureSetLabel": model_name,                                # (3006,0002)
        "StructureSetName": model_name,                                 # (3006,0004)
        "StructureSetDescription": f"Generated by {model_name}",        # (3006,0006)
        "ApprovalStatus": "UNAPPROVED",                                 # (300E,0002)
        "Manufacturer": "GSTT Clinical Scientific Computing",           # (0008,0070)
        "ManufacturerModelName": model_name,                            # (0008,1090)
        "InstitutionName": "Guy's and St Thomas' NHS FT",               # (0008,0080)
    }


def structure_names_from_dataset_json(dataset_json_path: str):
    """Return {mask value: structure name} from an nnU-Net dataset.json, w/o background.
       This maps pixel values in .nii.gz masks to structure names. 
    """

    with open(dataset_json_path) as jsonfile:
        labels = json.load(jsonfile)["labels"]

    return {int(value): name for name, value in labels.items() if int(value) != 0}


def write_contours_to_dicom(predictions_dir: str, dicom_dirs: dict, dataset_json_path: str,
                             output_dir: str, model_name = "<MODEL NAME>"):
    """Take all cases listed in dicoms_dir, write one RTSTRUCT per case
    from the predictions located in predictions_dir.

    Inputs:
        predictions_dir - folder of <case name>.nii.gz predictions
        dicom_dirs - {case name: image DICOM series folder}
        dataset_json_path - nnU-Net dataset.json, read for the structure names
        output_dir - folder to write <case name>.dcm into
        model_name - model name stamped onto the RTSTRUCTs, from [export] MODEL_NAME.
    """

    structure_names = structure_names_from_dataset_json(dataset_json_path)

    os.makedirs(output_dir, exist_ok=True)

    logger.info(
        f"Converting {len(dicom_dirs)} .nii.gz contours to RTSTRUCT. "
        f"structures: {list(structure_names.values())}"
    )

    for case_name, dicom_dir in sorted(dicom_dirs.items()):

        mask_path = os.path.join(predictions_dir, f"{case_name}.nii.gz")

        if not dicom_dir:
            logger.warning(f"no DICOM series found for {case_name}; skipping.")
            continue
        if not os.path.isfile(mask_path):
            logger.warning(f"no prediction at {mask_path} for {case_name}; skipping.")
            continue

        try:
            write_rtstruct(
                mask_nifti_path=mask_path,
                dicom_series_dir=dicom_dir,
                structure_names=structure_names,
                output_path=os.path.join(output_dir, f"{case_name}.dcm"),
                model_name=model_name,
            )
        except Exception:
            logger.exception(f"write_struct failed for {case_name}; continuing.")


def write_rtstruct(mask_nifti_path: str, dicom_series_dir: str, structure_names: dict,
                   output_path: str, model_name: str):
    """Write one DICOM RTSTRUCT from a multi-label NIfTI mask.

    Inputs:
        mask_nifti_path - multi-label mask (0 = background, 1..N = structures)
        dicom_series_dir - the image series the mask is aligned to
        structure_names - {mask value: structure name}
        output_path - .dcm file to write
        model_name - model name stamped onto the RTSTRUCTs, from [export] MODEL_NAME.

    Returns output_path, or None if every structure was empty.
    """

    nifti = nib.load(mask_nifti_path)

    # sort CT data, build empty structure that points at that CT
    rtstruct = RTStructBuilder.create_new(dicom_series_path=dicom_series_dir)

    # Reorient NIfTI data to match DICOM
    mask = reorient_mask_to_dicom(np.asanyarray(nifti.dataobj), rtstruct.series_data)

    # Truncate ROI names so they can be visualised in treatment planning systems -
    # this can be commented out if irrelevant to your use case.
    roi_names = roi_names_for_structures(structure_names)

    structures_added = []
    for value, _ in sorted(structure_names.items()):
        structure_mask = mask == value
        if structure_mask.any():
            rtstruct.add_roi(mask=structure_mask, name=roi_names[value])
            structures_added.append(roi_names[value])

    if not structures_added:
        logger.warning(f"every structure is empty in {mask_nifti_path}; nothing written.")
        return None

    # Modify RTSTRUCT metadata 
    tags = rtstruct_tags(model_name)
    apply_dicom_tags(rtstruct.ds, tags)

    # Round data to fit within decimal string limits then write to disk
    round_contour_data(rtstruct.ds)
    rtstruct.save(output_path)

    # Check what actually landed on disk, not what we meant to write: a value too long for its
    # value representation is truncated during serialisation, not when it is assigned.
    for problem in check_structure_set(pydicom.dcmread(output_path), tags):
        logger.warning(f"RTSTRUCT - {os.path.basename(output_path)}: {problem}")

    logger.info(f"RTSTRUCT - wrote {output_path}, structures: {structures_added}")

    return output_path


def roi_names_for_structures(structure_names: dict):
    """Format ROI names so they fit in treatment planning systems. 
    ROI name follows some rules:
    - has a maximum of MAX_ROI_NAME_LENGTH characters
    - if redundant names, replace last character by unique integer (1, 2, 3, ...)
    """

    trimmed = {value: name[:MAX_ROI_NAME_LENGTH] for value, name in structure_names.items()}
    clashes = Counter(trimmed.values())

    roi_names, numbered = {}, Counter()
    for value, name in sorted(structure_names.items()):
        roi_name = trimmed[value]

        if clashes[roi_name] > 1:
            numbered[roi_name] += 1
            suffix = str(numbered[roi_name])
            roi_name = name[:MAX_ROI_NAME_LENGTH - len(suffix)] + suffix

        roi_names[value] = roi_name

    return roi_names


def apply_dicom_tags(ds, tags: dict):
    """
    Modify metadata onto a finished structure set, and tags every ROI as automatically generated organ.
    May require adjustment for different applications.
    """

    for keyword, value in tags.items():
        setattr(ds, keyword, value)

    for structure_set_roi in ds.StructureSetROISequence:
        structure_set_roi.ROIGenerationAlgorithm = "AUTOMATIC"      # (3006,0036)

    for observation in ds.RTROIObservationsSequence:
        observation.RTROIInterpretedType = "ORGAN"                  # (3006,00A4)


def check_structure_set(ds, tags: dict):
    """Return a list of potential issues with the final RTstruct.
    """

    problems = []

    for keyword, expected in tags.items():
        actual = getattr(ds, keyword, None)
        if actual != expected:
            problems.append(f"{keyword} is {actual!r}, expected {expected!r}")

    for structure_set_roi in ds.StructureSetROISequence:
        if structure_set_roi.ROIGenerationAlgorithm != "AUTOMATIC":
            problems.append(
                f"ROI {structure_set_roi.ROINumber} ({structure_set_roi.ROIName}) has "
                f"ROIGenerationAlgorithm {structure_set_roi.ROIGenerationAlgorithm!r}"
            )

    for observation in ds.RTROIObservationsSequence:
        if observation.RTROIInterpretedType != "ORGAN":
            problems.append(
                f"ROI {observation.ReferencedROINumber} has "
                f"RTROIInterpretedType {observation.RTROIInterpretedType!r}"
            )

    # A contour needs 3 points to enclose an area; fewer usually means a stray voxel or two.
    for roi_contour in ds.ROIContourSequence:
        degenerate = sum(1 for contour in roi_contour.ContourSequence
                         if int(contour.NumberOfContourPoints) < 3)
        if degenerate:
            problems.append(
                f"ROI {roi_contour.ReferencedROINumber} has {degenerate} contour(s) "
                f"with fewer than 3 points"
            )

    return problems


def round_contour_data(ds):
    """Round every contour coordinate so it fits DICOM's 16-byte decimal string limit.
    """

    for roi_contour in ds.ROIContourSequence:
        for contour in roi_contour.ContourSequence:
            contour.ContourData = [round(coordinate, 10) for coordinate in contour.ContourData]


def reorient_mask_to_dicom(mask: np.ndarray, series_data: list):
    """Reorder a NIfTI mask array into the [row, column, slice] order rt-utils expects.

    The upstream dicom to NIfTI conversion is assumed to be a simple transpose - if
    this changes, contours will be wrong and function will need to be generalised.
    """

    reoriented = np.transpose(mask, (1, 0, 2)) # equivalent to rot90(mask, 3, (0, 1)) + flip(axis=1)

    reference_slice = series_data[0]
    expected_shape = (int(reference_slice.Rows), int(reference_slice.Columns), len(series_data))

    if reoriented.shape != expected_shape:
        raise ValueError(
            f"Mask shape {reoriented.shape} does not match the DICOM series "
            f"(rows, columns, slices) = {expected_shape}."
        )

    return reoriented
